package model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CHAT_MSG.
 */
public class ChatMsg {

    private Long id;
    private int memberId;
    private int contactId;
    /** Not-null value. */
    private String chatMsg;
    /** Not-null value. */
    private java.util.Date registerTime;
    private int chatType;
    private int isReceived;
    private int status;

    public ChatMsg() {
    }

    public ChatMsg(Long id) {
        this.id = id;
    }

    public ChatMsg(Long id, int memberId, int contactId, String chatMsg, java.util.Date registerTime, int chatType, int isReceived, int status) {
        this.id = id;
        this.memberId = memberId;
        this.contactId = contactId;
        this.chatMsg = chatMsg;
        this.registerTime = registerTime;
        this.chatType = chatType;
        this.isReceived = isReceived;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getMemberId() {
        return memberId;
    }

    public void setMemberId(int memberId) {
        this.memberId = memberId;
    }

    public int getContactId() {
        return contactId;
    }

    public void setContactId(int contactId) {
        this.contactId = contactId;
    }

    /** Not-null value. */
    public String getChatMsg() {
        return chatMsg;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setChatMsg(String chatMsg) {
        this.chatMsg = chatMsg;
    }

    /** Not-null value. */
    public java.util.Date getRegisterTime() {
        return registerTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRegisterTime(java.util.Date registerTime) {
        this.registerTime = registerTime;
    }

    public int getChatType() {
        return chatType;
    }

    public void setChatType(int chatType) {
        this.chatType = chatType;
    }

    public int getIsReceived() {
        return isReceived;
    }

    public void setIsReceived(int isReceived) {
        this.isReceived = isReceived;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

}
